### ISSUE TITLE
Generating JWT outside of HTTP lifecycle.

### ISSUE THREAD

**Issue by mikehhhhhhh** [adonisjs/adonis-auth#101]
Apologies, I wasn't sure where else to pose this question.

I find myself in need of generating JWT tokens outside of the HTTP lifecycle. 

Is there any way to get access to the `auth.generate` function outside of the http lifecycle?

**Comment by thetutlage** [comment]
What’s the use case?

**Comment by thetutlage** [comment]
Recently shared it here https://forum.adonisjs.com/t/how-to-get-access-to-auth-object-from-outside-of-the-request-cycle/898/7?u=virk
