### ISSUE TITLE
Proposal to add Cookie scheme

### ISSUE THREAD

**Issue by moltar** [adonisjs/adonis-auth#103]
I realize there is already a Session scheme, which utilizes cookies. However, I propose to add another scheme that uses cookies directly, without session.

I explain my rationale.

When building isomorphic apps, during server-side rendering, most of the time there is a need to have an authenticated request to the API. E.g. Apollo client making a request server-side to fetch some data for user account.

This can be solved by passing the necessary headers (e.g. `Authorization: ...` or `Cookie`) to the underlying client library (e.g. Apollo client via `fetch`).

However, when using session storage, there are some issues.

1. If a server-rendered page makes several requests to the API, and passes session cookie header, the returned cookies are conflicted due to Session scheme re-encrypting the cookies on each response. Now it is not clear which cookie should be passed back to the browser, if at all.

2. It gives as wrong impression to the developer that sessions are ok to use. But again, in the example above, when a page is constructed from multiple API queries and each API response modifies the session independently, we arrive at multiple session states at the end of the SSR request. Now what is supposed to happen and how these sessions should merge before sending rendered response back to the browser?

I think it could be a simple solution to just use an encrypted cookie to store an identifier. The implementation could be very similar to the session one, with the exception of using cookie store directly, rather than putting the auth object/data on the session.

Thoughts?

**Comment by thetutlage** [comment]
Since `auth` cookies are used during login or logout. I don't see any use case, where a single client will make 2 parallel requests to login and logout at the same time.
