### ISSUE TITLE
[Request] Missing doc for testing api using 'api' auth scheme

### ISSUE THREAD

**Issue by feryardiant** [adonisjs/adonis-auth#104]
As [documentation](http://adonisjs.com/docs/4.1/api-tests#_authentication) said about authenticate user while testing, I expect `loginVia` method treating any token-based authentication the same way and in this case I'm using [personal api scheme](http://adonisjs.com/docs/4.1/authentication#_personal_api_tokens) as default. Which mean I could test my end-point this way

```js
test('Get Some Data', async ({ client }) => {
  const user = await User.first()
  const response = await client.get('/end-point')
    .accept('json')
    .loginVia(user)
    .end()

  response.assertStatus(200)
  response.assertJSONSubset(expectedData)
})
```

But when I take a look at `src/Schemes/Api` it request a string instead of `User` Instance.

https://github.com/adonisjs/adonis-auth/blob/5e3e59bf761950651df6c6859794e287292fa50d/src/Schemes/Api.js#L199-L201

While the `src/Schemes/Jwt` we could simply pass the instance of `User`

https://github.com/adonisjs/adonis-auth/blob/5e3e59bf761950651df6c6859794e287292fa50d/src/Schemes/Jwt.js#L441-L444

The question is

1. Why both should be treated differently?
1. Why both couldn't accept 2 types of params, which is `string` of token or `User` instance? also
1. Why doc doesn't mention about `api` scheme?

Thanks & cheers 🥂

**Comment by thetutlage** [comment]
Yes, they should not be. Fixing it here https://forum.adonisjs.com/t/authenticating-rest-api-tests/972/2

**Comment by feryardiant** [comment]
Awesome! thanks so much @thetutlage.
