### ISSUE TITLE
Trouble with social auth

### ISSUE THREAD

**Issue by thomaslove** [adonisjs/adonis-auth#108]
```
/**
   * links an account with a google account
   * @return Response
   */
  async link ({ request, ally, view, auth, session }) {
    const token = request.input('token')
    const user = await User.findBy('link_token', token)
    if (!(user === null)) {
      await auth.login(user)
      const destination = await ally.driver('google').getRedirectUrl()
      return view.render('auth.redirect', { destination })
    }
  }
async callback ({ auth, view, session }) {
    try {
      let user = await auth.getUser()
      return user
    } catch (err) {
      return 'Not logged in!'
    }
  }
```
I've set up a flow that gives a user a link in an email which they can use to link their account to a Google account.

As you can see above the link function gets called, we log the user in (which works, we can verify this in a new tab) and then redirect them to the auth login page. (Doing this through a body(onload=window.location...) to allow cookies to be written.

Problem is, when the callback gets called I get E_INVALID_SESSION. Now I thought this was a problem with cross site cookies so I changed cookie:sameSite to false in config.js as well still nothing.

If I attach callback to a separate route and call it from another tab I can get it to return the user object.

Any ideas?

**Comment by RomainLanz** [comment]
Hey @thomaslove! 👋 

This doesn't seem to be a bug within Adonis.
Please, use the Discord Server or the forum to ask those question.

**Comment by RomainLanz** [comment]
Closing since issue hasn't been active for a while.
Feel free to create a new one if needed.
