### ISSUE TITLE
Add `allowGuest` param?

### ISSUE THREAD

**Issue by wxs77577** [adonisjs/adonis-auth#109]
Some routes can be accessed by guests and signed users, so we need an `auth` middleware but if there is a guest we shouldn't throw an error.

What I want is: 
```javascript
Route.get('/posts', 'PostController').middleware(['auth:jwt,allowGuest'])
```
Or is there another way to do this?
If not, I can make some changes and submit a PR.

**Comment by thetutlage** [comment]
How do you define a guest?

**Comment by wxs77577** [comment]
e.g: GET `/posts` and returns:
```json
{
  "_id": "asdf23sf234dsd",
  "title": "Post1",
  "is_liked": false
}
```
`is_liked` is `false` for **guests**(not login) or users DONT LIKED this post.
`is_liked` is `true` for login users LIKED this post.

**Comment by thetutlage** [comment]
Don't put a middleware on route, and simply use the `auth` object in the controller to see if user is loggedin.

```
const isLoggedIn = false

try {
  auth.authenticator('jwt').check()
  isLoggedIn = true
} catch (error) {}

// your code
if (isLoggedIn) {

}
```

If you want, you can drop this code in a middleware and simply set `isLoggedIn` on the `ctx`.

**Comment by wxs77577** [comment]
@thetutlage thanks. I will add a middleware.
