### ISSUE TITLE
InvalidLoginException (401) Login Failure

### ISSUE THREAD

**Issue by turlup** [adonisjs/adonis-auth#11]
Hi,

I try to implement basic auth.

config/auth.js :
```
  authenticator: 'basic',
```
```
  basic: {
    serializer: 'Lucid',
    model: 'App/Model/User',
    scheme: 'basic',
    uid: 'tel',
    password: 'code'
  },
```

routes.js :
```
Route.get('/profile', 'UserController.profile').middleware('auth:basic')
```

I have a "InvalidLoginException (401) Login Failure". I use Postman with "Basic Auth" option.

Any ideas ?

Thanks for your help.

**Comment by thetutlage** [comment]
Do you have `tel` and `code` fields in your users table? and are you passing them as headers when making the Http request.

**Comment by thetutlage** [comment]
Also it will be great, if you can share the CURL request

**Comment by turlup** [comment]
Yes, users table is OK.

`
curl -X GET -H "Authorization: Basic MDY3NzQ0NzE1NzoxMjM0" -H "Cache-Control: no-cache" -H "Postman-Token: 608bd53d-7075-907d-f6b3-46329c029042" "http://localhost:3333/api/1.0.0/profile"
`

**Comment by thetutlage** [comment]
@turlup  Can u share what's in the `users` table.

**Comment by turlup** [comment]
Create statements :
```
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `firstname` varchar(45) DEFAULT NULL,
  `lastname` varchar(45) DEFAULT NULL,
  `tel` varchar(10) NOT NULL,
  `code` varchar(4) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `state` enum('BANNED','PENDING_SMS','VALIDATED') NOT NULL DEFAULT 'PENDING_SMS',
  `confirm_tel` tinyint(1) NOT NULL DEFAULT '0',
  `confirm_email` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_tel_unique` (`tel`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
```
Content : 
`
'1', 'Jason', 'Flowers', '123456789', '1234', 'wekzovo@dad.ci', 'VALIDATED', '1', '1', '2016-07-21 13:25:36', '2016-07-21 13:25:36'
`

**Comment by thetutlage** [comment]
@turlup `password` field is supposed to be encrypted in the database using `Hash` provider.

**Comment by turlup** [comment]
Thanks @thetutlage you save my day. All is ok now !
Thanks for your amazing work.

**Comment by NetanelBasal** [comment]
But why it throws an exception, I think the correct behavior is just returning status 401

**Comment by javy1103** [comment]
@NetanelBasal You need to create your own middleware class register it, extend the middleware Auth class and changed the handle signature with the following. 

```
    * handle (request, response, next) {
        const args = Array.prototype.slice.call(arguments)
        const authenticators = args.length > 3 ? args.splice(3, args.length) : ['default']
        try {
            yield this._authenticate(request, authenticators)
        } catch (e) {
            response.status(401).send({ error: 'Please login first' })
            return
        }
        yield next
    }
```

Catch the error thrown by authenticate `generator` and respond accordingly.

**Comment by thetutlage** [comment]
@NetanelBasal @javy1103 There is no need to create another middleware. You simply should listen for Http errors.

Here are the docs http://adonisjs.com/docs/3.1/error-and-exceptions#_catching_exception

The point is to check for`InvalidLoginException` and return a formatted error.

```javascript
if (error.name === 'InvalidLoginException') { 
    return response.status(401).send('Invalid Login')
}
```

**Comment by javy1103** [comment]
@thetutlage Awesome, is all about reading the docs... Thanks a lot

**Comment by javy1103** [comment]
@thetutlage Is it possible to revoke users tokens while using jwt scheme?
