### ISSUE TITLE
adonis-remember-token cookie path issue

### ISSUE THREAD

**Issue by 9636565** [adonisjs/adonis-auth#115]
Hi, when I authenticate users with below code 'adonis-remember-token' cookie is set with path '/api/auth' but I want path to be '/'
```
Route.post('api/auth/login', async ({ request, response, auth }) => {
  const data = request.only(['uid', 'password', 'remember'])

  const user = await Persona.verify(data)

  await auth.remember(data.remember).login(user)

  response.json({
    message: 'successfully logged in.'
  })
})
```

My session.js config file is;
```
cookie: {
    httpOnly: true,
    sameSite: true,
    path: '/'
},
```

I looked at source and below code can set path to '/' if i make this small change.

\auth\src\Schemes\Session.js
```
_setSession (primaryKeyValue, rememberToken, duration) {
    ...
	
    if (rememberToken && duration) {
      this._ctx.response.cookie(this.rememberTokenKey, rememberToken, {
        expires: new Date(Date.now() + duration),
        **path: '/'**
      })
    }
}
```

But with this change, when i try to logout "adonis-remember-token" cookie still accessible.
To delete the cookie this line must added;

\framework\src\Response\index.js
```
clearCookie (key) {
    nodeCookie.clear(this.response, key, {
	**path: '/'**
    })
}
```

I think this methods should make use of session config file.

**Comment by thetutlage** [comment]
Agree! Want to make a PR for same?
