### ISSUE TITLE
Jwt: User is able to create jwt token when uid is equal to false

### ISSUE THREAD

**Issue by renzosunico** [adonisjs/adonis-auth#118]
We have a bug in our app which sets the value of uid to false in each request. Surprisingly, a valid token is given after the request.

We can  workaround this by not accepting boolean values in our app.

Sample postman request:

![auth](https://user-images.githubusercontent.com/13325504/41535398-bfa88eae-7334-11e8-88ca-e0c63448f829.png)

**Comment by thetutlage** [comment]
From the screenshot, I can see value for field `origin` is set to `false`. Where in the code you use this value to generate the token?

**Comment by renzosunico** [comment]
We have the following configuration:

```  jwt: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'jwt',
    uid: 'origin_url',
    password: 'secret_key',
    options: {
      algorithm: 'HS256',
      secret: Env.get('APP_KEY'),
      expiresIn: 60 * 60 * 2 // 2 hours
    }
  }```

In our controller:

``` const originUrl = request.input('origin_url')
    const secretKey = request.input('secret_key')

      const tokens = await auth
        .withRefreshToken()
        .attempt(originUrl, secretKey)```

If `originUrl` is equal to `false`, it returns a valid token.

**Comment by thetutlage** [comment]
Which isn't incorrect.

So `origin_url` is a field inside the database. The auth module simply queries the field based off the current value.

If your database has a row with the value of `false` inside it, they query will be considered successful and hence a token is generated for same.

**Comment by renzosunico** [comment]
We don't have an origin_url with false value in our database and it only happens when origin_url is boolean false. It doesn't create a valid token when origin_url is set to string false.

**Comment by thetutlage** [comment]
Okay that's interesting.

Can you share the SQL query created when `boolean (false)` is used. You can turn on database debugging by setting `debug: true` inside `config/database.js` file
