### ISSUE TITLE
Separated auth for admin, user models

### ISSUE THREAD

**Issue by Ali-Azmoud** [adonisjs/adonis-auth#121]
Hi

Is it possible to have separated auth for different models ? 
I have two different table for admins and users. and want to have separated auth with the same scheme for them.
How can I implement this in adonis js ?

**Comment by thetutlage** [comment]
Yes, it's 100% possible.

- Let's say you have 2 models. `App/Models/User` and `App/Models/Admin`
- Inside your `config/auth.js`, you can create multiple authenticators for `admin` and `user`.

```js
{
	user: {
	    serializer: 'lucid',
	    model: 'App/Models/User',
	    scheme: 'session',
	    uid: 'email',
	    password: 'password'
	},
	admin: {
	    serializer: 'lucid',
	    model: 'App/Models/Admin',
	    scheme: 'session',
	    uid: 'email',
	    password: 'password'
	}
}
```

And then to protect your routes, you can say.

```js
Route.get(...).middleware('auth:admin')
Route.get(...).middleware('auth:user')
```

If inside your controllers, you want to know if `user` is an `Admin` or just a `User`, you can use the following code.

```js
const Admin = use('App/Models/Admin')

if (auth.user instanceof Admin) {
  // user is admin
}
```

**Comment by Ali-Azmoud** [comment]
thanks for your detailed answer

**Comment by gitsakil09** [comment]
Even though you have answered in detail I haven't caught up everything.I am sorry I am new in adonis and its my first project using adonis and of course I am loving it because I have been working on laravel for 3/4 years.It would be great if you show this multiple login using multiple table from start to end.Please i have seen that its a concern to many developers. please @thetutlage

**Comment by wemersonrv** [comment]
> Yes, it's 100% possible.
> 
> * Let's say you have 2 models. `App/Models/User` and `App/Models/Admin`
> * Inside your `config/auth.js`, you can create multiple authenticators for `admin` and `user`.
> 
> ```js
> {
> 	user: {
> 	    serializer: 'lucid',
> 	    model: 'App/Models/User',
> 	    scheme: 'session',
> 	    uid: 'email',
> 	    password: 'password'
> 	},
> 	admin: {
> 	    serializer: 'lucid',
> 	    model: 'App/Models/Admin',
> 	    scheme: 'session',
> 	    uid: 'email',
> 	    password: 'password'
> 	}
> }
> ```
> 
> And then to protect your routes, you can say.
> 
> ```js
> Route.get(...).middleware('auth:admin')
> Route.get(...).middleware('auth:user')
> ```
> 
> If inside your controllers, you want to know if `user` is an `Admin` or just a `User`, you can use the following code.
> 
> ```js
> const Admin = use('App/Models/Admin')
> 
> if (auth.user instanceof Admin) {
>   // user is admin
> }
> ```

Hello. And about refresh token methods? Because the **Token** model is related to User not to Admin. And believe the auth implementations goes through it right ?

**Comment by fabiantorresm** [comment]
Thanks you. This is my file auth.js

'use strict'

/** @type {import('@adonisjs/framework/src/Env')} */
const Env = use('Env')

module.exports = {
  /*
  |--------------------------------------------------------------------------
  | Authenticator
  |--------------------------------------------------------------------------
  |
  | Authentication is a combination of serializer and scheme with extra
  | config to define on how to authenticate a user.
  |
  | Available Schemes - basic, session, jwt, api
  | Available Serializers - lucid, database
  |
  */
  authenticator: 'jwt',

  /*
  |--------------------------------------------------------------------------
  | Session
  |--------------------------------------------------------------------------
  |
  | Session authenticator makes use of sessions to authenticate a user.
  | Session authentication is always persistent.
  |
  */
  session: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'session',
    uid: 'email',
    password: 'password'
  },

  /*
  |--------------------------------------------------------------------------
  | Basic Auth
  |--------------------------------------------------------------------------
  |
  | The basic auth authenticator uses basic auth header to authenticate a
  | user.
  |
  | NOTE:
  | This scheme is not persistent and users are supposed to pass
  | login credentials on each request.
  |
  */
  basic: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'basic',
    uid: 'email',
    password: 'password'
  },

  /*
  |--------------------------------------------------------------------------
  | Jwt
  |--------------------------------------------------------------------------
  |
  | The jwt authenticator works by passing a jwt token on each HTTP request
  | via HTTP `Authorization` header.
  |
  */
  jwt: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'jwt',
    uid: 'email',
    password: 'password',
    options: {
      secret: Env.get('APP_KEY')
    }
  },

  /*
  |--------------------------------------------------------------------------
  | Api
  |--------------------------------------------------------------------------
  |
  | The Api scheme makes use of API personal tokens to authenticate a user.
  |
  */
  api: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'api',
    uid: 'email',
    password: 'password'
  },
  user: {
      serializer: 'lucid',
      model: 'App/Models/User',
      scheme: 'jwt',
      uid: 'email',
      password: 'password',
      options: {
        secret: Env.get('APP_KEY')
      }
    },
    admin: {
      serializer: 'lucid',
      model: 'App/Models/User',
      scheme: 'jwt',
      uid: 'email',
      password: 'password',
      options: {
        secret: Env.get('APP_KEY')
      }
    }
}

**Comment by juhguu** [comment]
What if I want to save / read the tokens on a different table?

**Comment by fabiantorresm** [comment]
you just want to change the name to the table or add another?

**Comment by italofelipe** [comment]
> Yes, it's 100% possible.
> 
> * Let's say you have 2 models. `App/Models/User` and `App/Models/Admin`
> * Inside your `config/auth.js`, you can create multiple authenticators for `admin` and `user`.
> 
> ```js
> {
> 	user: {
> 	    serializer: 'lucid',
> 	    model: 'App/Models/User',
> 	    scheme: 'session',
> 	    uid: 'email',
> 	    password: 'password'
> 	},
> 	admin: {
> 	    serializer: 'lucid',
> 	    model: 'App/Models/Admin',
> 	    scheme: 'session',
> 	    uid: 'email',
> 	    password: 'password'
> 	}
> }
> ```
> 
> And then to protect your routes, you can say.
> 
> ```js
> Route.get(...).middleware('auth:admin')
> Route.get(...).middleware('auth:user')
> ```
> 
> If inside your controllers, you want to know if `user` is an `Admin` or just a `User`, you can use the following code.
> 
> ```js
> const Admin = use('App/Models/Admin')
> 
> if (auth.user instanceof Admin) {
>   // user is admin
> }
> ```

I tried to implement my routes as you did, but in the end it returned this error.
![Erro](https://user-images.githubusercontent.com/25833906/56308581-09a17480-611e-11e9-89fd-0e1525034f24.png)

**Comment by filemoncesar** [comment]
> https://github.com/adonisjs/adonis-auth/issues/121#issuecomment-409090501

did not work for me. I did the implementation exactly as described, but I login with Ally and at the end I use `auth.login(allyuser),` so far it's ok the `auth.getUser()` points to a USER model.


But if I access a route that has the `middleware(['auth: admin'])` soon after logging in with a USER and then redo `auth.getUser()`, it automatically flips an instance of the ADMIN model. I noticed that this only happens if the ADMIN ID and the USER ID are the same

**Comment by nir-jas** [comment]
> Yes, it's 100% possible.
> 
> * Let's say you have 2 models. `App/Models/User` and `App/Models/Admin`
> * Inside your `config/auth.js`, you can create multiple authenticators for `admin` and `user`.
> 
> ```js
> {
> 	user: {
> 	    serializer: 'lucid',
> 	    model: 'App/Models/User',
> 	    scheme: 'session',
> 	    uid: 'email',
> 	    password: 'password'
> 	},
> 	admin: {
> 	    serializer: 'lucid',
> 	    model: 'App/Models/Admin',
> 	    scheme: 'session',
> 	    uid: 'email',
> 	    password: 'password'
> 	}
> }
> ```
> 
> And then to protect your routes, you can say.
> 
> ```js
> Route.get(...).middleware('auth:admin')
> Route.get(...).middleware('auth:user')
> ```
> 
> If inside your controllers, you want to know if `user` is an `Admin` or just a `User`, you can use the following code.
> 
> ```js
> const Admin = use('App/Models/Admin')
> 
> if (auth.user instanceof Admin) {
>   // user is admin
> }
> ```

I am using Adonis Ally. In this case what should be the config for default authenticator.

**Comment by IBatistaSantos** [comment]
Hello, I have a problem, I'm developing with adonisjs and I can't generate a JWT with multi models. 
I followed the suggested implication, but it doesn't work

**Comment by Davidiasdesousa** [comment]
> Hello, I have a problem, I'm developing with adonisjs and I can't generate a JWT with multi models.
> I followed the suggested implication, but it doesn't work

1º: auth.js
`
  authenticator: "**admin**", <---

admin: {
    serializer: "lucid",
    model: "App/Models/Admin", <--ADMIN MODEL
    scheme: "jwt",
    uid: "email",
    password: "password",
    options: {
      secret: Env.get("APP_KEY_AUTH_ADMIN"), <-- DIFF APP KEY
      expiresIn: 3600000
    }
  },

  user: {
    serializer: "lucid",
    model: "App/Models/User", <-- USER MODEL
    scheme: "jwt",
    uid: "email",
    password: "password",
    options: {
      secret: Env.get("APP_KEY"), <-- DIFF APP KEY
      expiresIn: 3600000
    }
  },
`

2º: In your ADMIN / USER auth controller
`   async store({ request, auth }) {
    const { email, password } = request.all();
    const adminAuth = auth.authenticator("admin");
    const token = await adminAuth.attempt(email, password);
    return {
      success: true,
      data: token
    };
  }`

3º: Protect your routes
`Route.get("user_profile", "User.show").middleware(
  "auth:user"
);
Route.get("admin_profile", "User.show").middleware(
  "auth:admin"
);`

**Comment by sotoh** [comment]
Do I have to create a different token table for each type of user?

**Comment by RoyNij** [comment]
> > [#121 (comment)](https://github.com/adonisjs/adonis-auth/issues/121#issuecomment-409090501)
> 
> did not work for me. I did the implementation exactly as described, but I login with Ally and at the end I use `auth.login(allyuser),` so far it's ok the `auth.getUser()` points to a USER model.
> 
> But if I access a route that has the `middleware(['auth: admin'])` soon after logging in with a USER and then redo `auth.getUser()`, it automatically flips an instance of the ADMIN model. I noticed that this only happens if the ADMIN ID and the USER ID are the same

I am loving adonis js, but I have the same issue as described above. As far as I can tell (an do correct me if I'm wrong) the authenticator only identifies a user/admin by primary key. So a logged in user can be mistaken for an administrator if the primary keys are the same. Has anyone found a way around this, because I think there might be valid reasons to have different types of users (in my case app administrators and app clients) in different tables.

**Comment by creativster** [comment]
What about Tokens, how can we setup the datatables to issued refresh tokens to multiple models?

**Comment by msrumon** [comment]
Is this achievable in v5 of AdonisJS?

**Comment by tincho425** [comment]
> 1º: auth.js
> 
>  authenticator: "admin", <---
> 
> admin: {
>     serializer: "lucid",
>     model: "App/Models/Admin", <--ADMIN MODEL
>     scheme: "jwt",
>     uid: "email",
>     password: "password",
>     options: {
>       secret: Env.get("APP_KEY_AUTH_ADMIN"), <-- DIFF APP KEY
>       expiresIn: 3600000
>     }
>   },
> 
>   user: {
>     serializer: "lucid",
>     model: "App/Models/User", <-- USER MODEL
>     scheme: "jwt",
>     uid: "email",
>     password: "password",
>     options: {
>       secret: Env.get("APP_KEY"), <-- DIFF APP KEY
>       expiresIn: 3600000
>     }
>   },
> 2º: In your ADMIN / USER auth controller
> 
> async store({ request, auth }) {
>     const { email, password } = request.all();
>     const adminAuth = auth.authenticator("admin");
>     const token = await adminAuth.attempt(email, password);
>     return {
>       success: true,
>       data: token
>     };
>   }
> 3º: Protect your routes
> 
> Route.get("user_profile", "User.show").middleware(
>   "auth:user"
> );
> Route.get("admin_profile", "User.show").middleware(
>   "auth:admin"
> );

@Davidiasdesousa thanks to explain with an example, that was extremely useful.
Just for being thankful, a comment on how I solve a issue I had in this topic.

An example of a group of endpoints and middlaware applied with this auth.js configuration is:

```
Route.group(() => {
    Route.get('/', 'ExampleController.functionName')
    Route.post('/endpoint', 'ExampleController.functionNameExample')
}).middleware(['auth:user,admin'])
```

**Comment by junicodes** [comment]
Thank you for all of this

**Comment by tridungle** [comment]
thank you very much!

**Comment by kavita615** [comment]
How can I implement this in the adonisJs version 5?

**Comment by kaushikabhi999** [comment]
How can we achieve this in version 5?

**Comment by hamzabawumia** [comment]
@loggedIn does not work for admin user since it seems to be checking only the default user model. Kindly help.

`

...@section('content') @loggedIn <a href="logout">Log out</a> @else <a href="login">Log in</a> <a href="register">Register</a> @endloggedIn
--


`
