### ISSUE TITLE
The bearer token does not expire or invalidated when the server is stopped or even the database is refreshed and reseeded

### ISSUE THREAD

**Issue by wqqas1** [adonisjs/adonis-auth#127]
The bearer token does not expire or invalidated when the server is stopped or even the database is refreshed and reseeded 

## Package version
3.0.4

## Node.js and npm version
npm version 6.4.1
Node.js version 
10.11.0

## Sample Code (to reproduce the issue)
see the git link below run the migrations and seed
```javascript
adonis serve --dev
```
I am using Insomnia to test the rest routes so then bearer token is generated 
![screen shot 2018-10-09 at 1 47 42 am](https://user-images.githubusercontent.com/20567910/46632907-92cf6180-cb65-11e8-933f-6409349beef4.png)

Now use this bearer token to perform any action that is protected by Auth
![screen shot 2018-10-09 at 1 51 08 am](https://user-images.githubusercontent.com/20567910/46632993-d629d000-cb65-11e8-8081-707e73a4b9a2.png)

And you can see that the result is returned fine which is good now
![screen shot 2018-10-09 at 1 52 58 am](https://user-images.githubusercontent.com/20567910/46633264-a3340c00-cb66-11e8-84b9-91b4d23c3961.png)

```
adonis migration:refresh
adonis seed
adonis serve --dev
```
Try to access the Auth protected route again with the same old bearer value in header
![screen shot 2018-10-09 at 1 59 04 am](https://user-images.githubusercontent.com/20567910/46633429-0c1b8400-cb67-11e8-9531-570518ca8145.png)
In the profileController I am using auth to retreive the loggedin user. which should not work as that bearer token is not valid anymore but still it is retrieving that information
![screen shot 2018-10-09 at 2 00 57 am](https://user-images.githubusercontent.com/20567910/46633554-7502fc00-cb67-11e8-8449-f9fbc53fd919.png)
 

 
## BONUS (a sample repo to reproduce the issue)
https://github.com/xtrunks/vuetify-asterisk-admin.git

**Comment by RomainLanz** [comment]
Hey @wqqas1! 👋 

I recommend you to learn more about [how a JWT works](https://jwt.io/) because this is the expected behaviour.
If you need to invalidate/revoke you may want to consider using an alternative of JWT.

As a quick overview:
- JWT’s are not stored on the server.
- Once the user has the token, they can use it until it expires.
- That’s why it’s recommended to keep the expiry short.
