### ISSUE TITLE
Cannot verify token via algorithm RS256

### ISSUE THREAD

**Issue by ivybridge-3c33** [adonisjs/adonis-auth#130]
Cannot verify token via algorithm RS256
it's working ok when request token but when verify token on function
` auth.check() `

it's showing up

` InvalidJwtToken: E_INVALID_JWT_TOKEN: invalid algorithm`

ON Auth.js setting
```
jwt: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'jwt',
    uid: 'email',
    password: 'password',
    options: {
      algorithm: 'RS256',
      secret: fs.readFileSync(__dirname + '/../oauth-private.key'),
      expiresIn: (60*60*24*7),
      notBefore: (60*60*24*10),
      subject: "blablabla",
    }
  }
```

Please help

**Comment by RomainLanz** [comment]
Hey @ivybridge-3c33! 👋 

Thanks for your patience.
Could you please provide a repository with a test and with the minimum amount of code so we can reproduce the issue?

**Comment by kal72** [comment]
this also happened to me.

**Comment by kal72** [comment]
where to set the public key? fs.readFileSync('path-to-public-key')

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
