### ISSUE TITLE
expiresAt missing from 

### ISSUE THREAD

**Issue by narwy** [adonisjs/adonis-auth#134]
`await auth.withRefreshToken().generate(user)`

Returns:
```
refreshToken: "tokenXYZ"
token: "tokenXYZ"
type: "bearer"
```

But no expiresAt key? This is needed to use the refresh token on a new request? Most apps do a axios call using beforeRequest check that the token is expired, if it is expired use the refresh token to generate a new token etc.

**Comment by marines** [comment]
Isn't `expireAt` in the token?

**Comment by narwy** [comment]
It should be passed as another attribute outside the token, that way your app doesn't need to reply on decrypting the JWT to get a vital piece of information which can be passed from the server side.

**Comment by thetutlage** [comment]
The entire point of JWT token is to have the option of decrypting and pulling the vital info from the token.

I am not in favor of putting expiresAt as top level key.

**Comment by narwy** [comment]
@thetutlage then why do other major frameworks support this. Why decompile the access token in full oauth when you just pass that data back as a bearer which should be decompile services to validate the token. Laravel does this method and most oauth services also offer this entry key as standard. No point in having a frontend app decompiling a token of its not required.

**Comment by narwy** [comment]
https://tools.ietf.org/html/rfc6749
