### ISSUE TITLE
Tutorial about adding Oauth?

### ISSUE THREAD

**Issue by connor11528** [adonisjs/adonis-auth#16]
I would like to build apps with Adonis.js that feature "Login with Linkedin" or "Login with Spotify".

Is there a tutorial out there to help developers build oauth applications with Adonis? What are the steps involved?

Thank you! 

PS
I followed the [Auth0 tutorial](https://auth0.com/blog/creating-your-first-app-with-adonisj-and-adding-authentication/) by @unicodeveloper and it was very helpful with adding email/password auth. Now wondering about social login

**Comment by thetutlage** [comment]
@connor11528 Ofcourse you can build Oauth login using the vendor specific SDK's. If you are looking for a more streamline in-built solution, I am afraid there is no official package for that.

I am currently working on it and you can expect it to be launched in next 15-20days.

**Comment by connor11528** [comment]
Awesome thank you so much!

**Comment by theobouwman** [comment]
@thetutlage are you still working on the OAuth implementation, for Facebook specific?

**Comment by thetutlage** [comment]
@theobouwman Yes, it is at the top of my tasks list after `3.1` release.

**Comment by theobouwman** [comment]
@thetutlage can you give me an indication how long we have to wait for it? I'm willing to help

**Comment by thetutlage** [comment]
@theobouwman May be around a week or 10days.

**Comment by theobouwman** [comment]
@thetutlage okay nice.

**Comment by theobouwman** [comment]
Any updates on this question?

**Comment by thetutlage** [comment]
Adonis ally has been released a while ago http://adonisjs.com/docs/3.1/social-auth
