### ISSUE TITLE
Mongo serializer?

### ISSUE THREAD

**Issue by picorelli** [adonisjs/adonis-auth#17]
Hello! Does it possible to create a Mongo Serializer to use with Auth package? Or Does it possible to use Auth module without Serializer?

Thank you!

**Comment by thetutlage** [comment]
@picorelli Yes it is possible to extend the auth provider and add your own serializer. Without serializer authentication is of no use. 

I will add the docs for extending the auth provider soon.

**Comment by picorelli** [comment]
@thetutlage. Thank you!! :)

**Comment by thetutlage** [comment]
Added here http://adonisjs.com/docs/3.1/authentication#_extending_auth_provider
