### ISSUE TITLE
JWT auth with attempt method

### ISSUE THREAD

**Issue by NetanelBasal** [adonisjs/adonis-auth#18]
I need to validate the user email and password, and if they are valid I want to send the JWT token, but the method "request.auth.attempt(email, password)" not working with JWT schema, there is a built way to do this, or I need to implement the logic myself?

**Comment by thetutlage** [comment]
You can switch the authenticator at runtime to validate the user credentials.

```javascript
const sessionAuth = request.auth.authenticator('session')
sessionAuth.attempt(email, password)
```

**Comment by NetanelBasal** [comment]
But this method creates a session no? ( I don't need and want session )

**Comment by thetutlage** [comment]
Use the `validate` method instead

**Comment by NetanelBasal** [comment]
Nice!

I am exploring the framework, and I love it.

But it took me a while and digging the source code to understand for example that the JWT schema requires the 'Bearer' prefix before the token and the "Authorization" header.

It will be great if you can add deeper documentation. Thanks.

**Comment by NetanelBasal** [comment]
This is fully working example of JWT authentication:

```js

'use strict'

const User = use('User');
const Hash = use('Hash')

class UserController {

  * signup(request, response) {
    const {
      email,
      password
    } = request.post();

    const user = yield User.create({
      email,
      password: yield Hash.make(password)
    });

    const token = yield this._generateToken(request, user);

    response.json({
      user,
      token
    });
  }

  * login(request, response) {
    const email = request.input('email');
    const password = request.input('password');
    const sessionAuth = request.auth.authenticator('session');
    try {
      yield sessionAuth.validate(email, password);
      const user = yield User.query().where('email', email).first();
      const token = yield this._generateToken(request, user);
      response.json({
        token,
        user
      });
    } catch (e) {
      response.unauthorized('Invalid credentails');
    }
  }

  * _generateToken(request, user) {
    return yield request.auth.generate(user);
  }

}

module.exports = UserController


``
I have notice to two things here:
1. I think the authenticator switcher is redundant, and the validate method also need to be on the JWT schema, because you can't send token unless you verify the email and password first.
2. The Hash.make function is pretty slow.

**Comment by RomainLanz** [comment]
> It will be great if you can add deeper documentation. Thanks.

This is planned! 😄

**Comment by thetutlage** [comment]
@NetanelBasal Will add the `validate` and `validateAndGenerate` methods to the JWT authenticator.

`Hash.make` is supposed to be slow, all hashing algo's are slow to prevent password hijaking. You can read more on *Why Bcrypt is slow?*

**Comment by NetanelBasal** [comment]
Good news. thanks.

I am coming from Laravel background too, and I love what you did with this framework.

**Comment by suchidomelo** [comment]
Hi , 
I have issue login to second time show error message 
"Password does not match" or Invalid Credentials

my controller code 

'use strict'

const User = use('App/Model/User')
const Hash = use('Hash')
const Mail = use('Mail')
const ResetHash = use('App/Model/ResetPasswordHash')
const Profile = use('App/Model/Profile')
const Env = use('Env')

class AuthController {

    * index(request, response) {
        
        yield response.sendView('index/login')
    }

     * fblogin (request, response) {
        const data = request.all()
        debugger;   
        if(data != null)
        {   
            var fbId = data.response.id;                 
            var profile = new Profile(),
            ownFbProfile = yield profile.getUserDetailsByFbId(fbId)            
       
          if(ownFbProfile[0].facebook_id != null)
          {

           // console.log(ownFbProfile[0].password)
            
            const email = data.response.email          
            const password = ownFbProfile[0].password
            var fbid = ownFbProfile[0].facebook_id

            const loginMessage = {
            success: 'Logged-in Successfully!',
            error: 'Invalid Credentials'
            }      

            try{

               
                console.log(email)
                console.log(password)

                //yield request.auth.attempt(email, password)
              const authCheck = yield request.auth.attempt(email, password)  
             
            } catch (e) {
                  response.unauthorized('Invalid credentails');
            }
                
            
            // Attempt to login with email and password           
          }

             response.status(200).json(ownFbProfile)
            
         // response.json(ownFbProfile)                  
        }

        if (authCheck) {
                return response.redirect('/')
                
        }
       yield response.sendView('index/login', { error: loginMessage.error })
        
                
    }
}

please give me any solution

**Comment by suchidomelo** [comment]
Hi am using Adonisjs

**Comment by RomainLanz** [comment]
Hey @suchidomelo!

May you create your own issue?
