### ISSUE TITLE
Characters in the token id generated is not equal to the varchar character limit in token table

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/adonis-auth#19]
@webreinvent commented on [Fri Sep 23 2016](https://github.com/adonisjs/adonis-framework/issues/288)

Here's what I did:

1) ```ace auth:setup``` to setup authentication, it created migration as well which includes tokens table.
2) Changed authenticator from ```authenticator: 'session',``` to ```authenticator: 'api',```
3) Used following code to generate token:
```javascript
const user = yield User.find(1)
const token = yield request.auth.generate(user)
```
if I print this token it contains 121 characters while in ```tokens``` table, column ```token``` has only ```varchar(40)``` 40 characters.

**Comment by thetutlage** [comment]
@webreinvent Can u share the generated token?

**Comment by webreinvent** [comment]
yeah sure ```eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjoxLCJpYXQiOjE0NzQ2NTMwODV9.KjwELbXTFiOdTIz3Ta8Vsv4rTbzxPZxxMvMX3MP-7Yo```

<img width="477" alt="token" src="https://cloud.githubusercontent.com/assets/3604392/18796347/6e7e81c8-81e6-11e6-821f-761d5ab12cee.PNG">

**Comment by thetutlage** [comment]
This is a JWT token for sure. Can u share the complete config file `config/auth.js`.

**Comment by webreinvent** [comment]
oh, my bad forgot to upload the changed config file to server. Sorry! You can close the issues.

can you guide me about how to make the api call? I am using php curl to get response ```<my api url>?token=<token>``` but how to authenticate using the token passed in the middleware?

**Comment by thetutlage** [comment]
It is then`Authentication` header `Bearer <API TOKEN>`
