### ISSUE TITLE
Multiple Auth like in laravel 5.3

### ISSUE THREAD

**Issue by zainul-realtime** [adonisjs/adonis-auth#21]
Does adonisjs have multiple auth like in laravel 5.3 ?
multiple auth its mean can use not only user table / model

for example:
use for employee table and customer table 

Thanks

**Comment by RomainLanz** [comment]
Hey @zainul-realtime !

This feature is not currently in the core of the framework but will be great to have it.
@thetutlage is currently in travelling and will decide if we should add it to the core of the framework.

**Comment by zainul-realtime** [comment]
Yap , this framework very nice , easy to use :dancer:  Hehe

**Comment by thetutlage** [comment]
Must part of forums, if needs more discussion
