### ISSUE TITLE
Password Does Not Match error

### ISSUE THREAD

**Issue by ais-one** [adonisjs/adonis-auth#25]
Hi,

I tried to do JWT, when running the validate command I get the above result.

In the DB, email is aaron@abc.com, password is 123456789 (unhashed)

Is the password supposed to be hashed in the database? If so, what is the hashing. The docs could improve on this as I spent a few hours trying to get this simple thing to work... but still failed...

**Comment by ais-one** [comment]
Hi,

I just went through the adonis-auth sources, and I saw the hash being done.

I managed to get it to work, and will close this. I will do a write up to improve the docs, please ignore my PR later if you feel there is no need to, so far I am liking the framework and hope it will improve over time with help from the community.

I have some basic knowledge on how laravel works, so moving around wasn't too hard. I am a user of Sequelize ORM but it took me alot of time to master the more complex part. Lucid looks easier and better and I hope to test drive the more complex things like relations

**Comment by thetutlage** [comment]
Fixed. The 5th point http://adonisjs.com/docs/3.1/authentication#_about_authentication

**Comment by Charada32** [comment]
I have the same question, @ais-one can answer me how you use auth when the password is not hash ou crypt?

**Comment by ais-one** [comment]
Hi

I decided to use expressjs instead and scaffold everything properly...

**Comment by RomainLanz** [comment]
Hey @Charada32! 👋 

You can create your own Authentication service. Retrieve the user, manualy check the password and set its ID in its session.
