### ISSUE TITLE
Enable client side hashing for any authentication

### ISSUE THREAD

**Issue by hajnalben** [adonisjs/adonis-auth#27]
I would like a way to verify the user's password which was hashed on the client-side with the same hashing library (bcryptjs).

The BaseScheme's `* validate (uid, password, returnUser)` method may check if the provided password is the same as the uid related user's before hashing it.

**Comment by thetutlage** [comment]
Nope not gonna happen. Passwords are hahed using a salt and if you are using the same salt on client then this is a security concern.

Also i am not going to add any features which are outside the scope of the framework

**Comment by hajnalben** [comment]
It may be security concern when you send plain passwords through HTTP too. Using HTTPS could be the solution then.
Thanks for your reply.

**Comment by thetutlage** [comment]
It's not about sending password. It is about keeping SALT on the client side, where anyone can peek into the JS file and use that SALT for decrypting cookies, sessions etc

**Comment by hajnalben** [comment]
Yeah, thats clear. But plain password can be eavesdropped.

**Comment by thetutlage** [comment]
Closing since not actionable and out of the scope of the framework. Feel free to create issues for in future concerns

**Comment by panzarino** [comment]
@thetutlage I would definitely mention somewhere in the docs that passwords are automatically hashed using a salt. The only place that I have found it mentioned is this issue from 3 years ago.
