### ISSUE TITLE
Is it possible to have multiple authentication methods at once?

### ISSUE THREAD

**Issue by thomaslove** [adonisjs/adonis-auth#28]
I've been reading the documentation on authentication methods. Is it possible to allow both session based authentication and API token authentication? It doesn't seem clear from the docs.

My idea is to have a webUI that uses session based authentication and a mobile app that uses token based authentication.

If I've missed some piece of documentation somewhere, please let me know. It seems like you can currently only select one however. Cheers!

**Comment by thetutlage** [comment]
Yup, you can by making use of the `auth` middleware. 

```
Route.get().middleware('auth:session,api')
```

Above will try to authenticate the user using both ways and will proceed if user satisfies one.

**Comment by thomaslove** [comment]
Brilliant, thanks! 😁

If it's not in the docs already, I may have missed it, please can we add this?

**Comment by RomainLanz** [comment]
PR are welcomed!

https://github.com/adonisjs/docs/pulls

**Comment by princenaman** [comment]
Just found out:
This works
```javascript
Route.get().middleware('auth:session,api')
```

This doesn't
```javascript
Route.get().middleware('api,auth:session')
```

Is it a bug or is it supposed to be this way?

**Comment by RomainLanz** [comment]
Hey @princenaman !

In the first example, `auth:session,api` mean that <ou are using the `auth` middleware and you a sending `session` and `api` to as parameters.

In the second example you are using the `api` and the `auth` middleware. That's different.

* [AdonisJs Documentation](http://adonisjs.com/docs/3.2/middleware)

**Comment by princenaman** [comment]
Is there a way I can use 2 middleware?
Like I have a custom middleware called acl where in I pass a parameter

This works correctly
```javascript
Route.get().middleware('acl:root')
```

Now I want to use the auth middleware before this like we could do in Laravel:
```
'middleware'   => ['auth', 'acl'],
```

So I tried
```javascript
Route.get().middleware('auth,acl:root')
```

But it gives error:
```
E_MISSING_NAMED_MIDDLEWARE: auth,acl is not registered as a named middleware
```

**Comment by thetutlage** [comment]
You can use a plain array

```
Route.get().middleware(['auth', 'acl:root'])
```

**Comment by princenaman** [comment]
Thanks!!

**Comment by thetutlage** [comment]
Closing since not actionable and answered the question

**Comment by Ra1da35ma** [comment]
Hi, my project is a bit complicated

I'm using `JWTAuth` for the API authentication and then `Auth` for Web

**Comment by outluch** [comment]
I have 2 types of users and auth systems respectfully: client lgged in by phone number and unique device id, and operator, who work on orders, received from clients. Operators should log in with email/password or maybe username/password. More classical. How can I define two JWT schemes? Or I should write my own implementation for one of schemes? (or copy from adonis auth middleware?

**Comment by thetutlage** [comment]
Do not reply to a closed issue please, instead create a new issue with specific details
