### ISSUE TITLE
Attempt method throws exception

### ISSUE THREAD

**Issue by gregbty** [adonisjs/adonis-auth#30]
Whenever auth.attempt is called for invalid state i.e. user not found or wrong password, the method will throw an exception. If the result of the method should return a boolean to represent whether or not the login attempt was successful, shouldn't the auth.attempt swallow the user not found and password mismatch errors thrown by the validate method?

**Comment by thetutlage** [comment]
Nope it should not and exceptions are required so that you can act upon by them by showing exact errors to the end user. 

For example on email not found, you can show the error message as this email doesn't exists.

Wheras swallowing errors means all can tell the end user is "login failure"

**Comment by gregbty** [comment]
So in what case would the attempt method ever return anything but true? Based on the documentation and the code it is not clear that I should rely on catching exceptions rather than just checking if the return value, a boolean, is true or false.

**Comment by thetutlage** [comment]
The docs seems to be quite clear. http://adonisjs.com/docs/3.2/authentication#_attempt_uid_password

If `attempt` does not throw exception, it means authentication went fine

**Comment by gregbty** [comment]
It looks like I was referring to the code comments for the Session scheme:

https://github.com/adonisjs/adonis-auth/blob/ca79a523bac3ebb73985281bc2fc6dd022aeac38/src/Schemes/Session/index.js#L101-L113

I will just use the official documentation going forward. Thanks!
