### ISSUE TITLE
Pass Extra Payload to JWT attempt()?

### ISSUE THREAD

**Issue by iamkether** [adonisjs/adonis-auth#38]
After the work done in #13, should there not be an additional parameter added to [JWT.attempt()](https://github.com/adonisjs/adonis-auth/blob/develop/src/Schemes/Jwt/index.js#L148-L151) to pass an optional user payload object since it uses `generate()` inside?

I can send a PR over for this, but just want to make sure I'm not missing/misunderstanding about `attempt()` before I do.

**Comment by thetutlage** [comment]
True, it should allow the custom payload as well

**Comment by iamkether** [comment]
Okay, I'll work on a PR in the next few days.

**Comment by thetutlage** [comment]
Merged
