### ISSUE TITLE
Custom API for authentication

### ISSUE THREAD

**Issue by marcohajek** [adonisjs/adonis-auth#41]
Hey,
how would i use my existing api for logging in? I'm currently using an API based on nodejs and mongodb.
The API works but I don't know how to integrate it the best way

**Comment by thetutlage** [comment]
Didn't get what you really mean by existing API. You mean you have a auth system already built in and wants to login a user with AdonisJs?

**Comment by marcohajek** [comment]
Lets say I have following api routes:
api
api/auth
api/users

with the api/auth route the user only gets a jwt token when the user data is correct.
My thought is, when i already have an auth system, how is it possible to use it with adonisjs

**Comment by thetutlage** [comment]
Yes, you can do it by binding middleware to each of them and each middleware uses a different authenticator.

Example

```js
Route
.group('api')
.middleware(['auth:session'])
```

```js
Route
.group('api/auth')
.middleware(['auth:jwt'])
```

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
