### ISSUE TITLE
Authetication required to access files?

### ISSUE THREAD

**Issue by GreWull** [adonisjs/adonis-auth#42]
Hi!

I was wondering if there is a simple way to protect the files on the server (e.g PDF).

By "protect" I mean that the user must be logged in order to access the file.

At the moment I've a simple Article model which contains a Title, Description and the PDF name. Then there is a controller which simply show these information with the embedded PDF, so the user can access view the PDF with foo.com/article/{id} and here I have the Auth middleware.

But it could also access it by foo.com/PDF_Name.pdf without authentication, and it's what I want to avoid.

**Comment by thetutlage** [comment]
You can store the pdf file somewhere else, instead of storing it inside the `public` directory. One option is to keep it inside the `storage` directory.

Then write a route, which is authenticated by the `auth` middleware and manually download the file.

## Minimal Example
```js
Route.get('/file/:name', * function (request, response) {
  const filePath = Helpers.storagePath(request.param('name'))
  response.download(filePath)
}).middleware('auth')
```

**Comment by GreWull** [comment]
Worked perfectly! Thanks for quick answer :)

Just a small typo:
Should be 

`function * (request, response)`

instead of 

`* function(request, response)`

**Comment by thetutlage** [comment]
Yup dump typo
