### ISSUE TITLE
revokeAll(user) revoking all tokens of all users

### ISSUE THREAD

**Issue by marceloLiberton** [adonisjs/adonis-auth#43]
Hello folks.

Basically the title explains everything. I'm using it that way:

`const user = yield User.query().where({ username }).first()`
`yield request.auth.revokeAll(user)`

And when I check in sqlite, all tokens, of all users, have been revoked, not only the tokens of the current queried user.

I'm using the code below instead of revokeAll:
`yield Token.query().where({ 'user_id': user.id }).update({ 'is_revoked': true })`

Am I using revokeAll wrong or it's a bug?

**Comment by thetutlage** [comment]
Can u share the query generated when you call `request.auth.revokeAll`. To log the queries just set
`debug: true` inside the database.js file for the connection your are using

**Comment by marceloLiberton** [comment]
Hi @thetutlage. The 2 queries (select user and revokeAll):

`
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'joao_alves', 1 ],
  __knexQueryUid: '4a74414e-7c9a-423b-b707-d61a1142ffcb',
  sql: 'select * from "users" where "username" = ? limit ?' }

{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ true, '2017-05-04 14:26:15' ],
  __knexQueryUid: 'f07d3af5-1a20-4f78-9603-03671dbb1bc5',
  sql: 'update "tokens" set "is_revoked" = ?, "updated_at" = ?' }
`

**Comment by thetutlage** [comment]
Yup it is generating wrong query, lemme see the issue and fix it

**Comment by thetutlage** [comment]
So the bug was in `adonis-lucid` over this package. Can u update `adonis-lucid` to 3.0.16 and share the debug output again?

**Comment by marceloLiberton** [comment]
@thetutlage worked like a charm. :)

( And, thanks for this framework, its awesome! \o/ )

**Comment by thetutlage** [comment]
Thanks for reporting the bug and closing the issue
