### ISSUE TITLE
How login user with Relations?

### ISSUE THREAD

**Issue by cawa-93** [adonisjs/adonis-auth#49]
My User model has `id`, `name` and `permissions` as Relations
```javascript
const user = yield User
  .query()
  .with('permissions') 
  .fetch()
```
```javascript
{
  "id": 1,
  "name": "Alex"
  "permissions": [/* ... */]
}
```
But after login `request.currentUser` has no `permissions` property. How create currentUser object with Relations? For example:
```javascript
request.auth.loginViaId(id).with('permissions') 
```

**Comment by thetutlage** [comment]
I believe you can create a middleware which eagerloads the relationships for you.

```js
* handle (request, response) {
  yield request.currentUser.related('permissions').load()
}
```

Inside controllers

```js
// pre loaded permissions
const permission = request.currentUser.get('permissions')
```

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter
