### ISSUE TITLE
Extending Auth Provider in Adonis 4

### ISSUE THREAD

**Issue by stecapra** [adonisjs/adonis-auth#65]
Hi,
i'm trying to extend auth provider to support mongoDB for authentication.
There is nothing about in the docs, but in 3.x docs yes. 
In particular, 3.x docs says that i have to extend auth provider adding a  ```Ioc.extend``` function in `bootstrap/extend.js`, but in 4.x there is no more bootstrap folder.
Where do i have to add the extend code?

Thank you

**Comment by RomainLanz** [comment]
Hey @stecapra! 👋 

You can use Ignitor's Hooks (http://dev.adonisjs.com/docs/4.0/ignitor#_hooks) to do that.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by footniko** [comment]
Would like to extend `auth.getUser()` data in Adonis 4.1. How can I do that best? Thanks.

**Comment by RomainLanz** [comment]
Hey @footniko! 👋 

You better create a middleware that run **after** `AuthInit`.
