### ISSUE TITLE
capitalize jwt token type  

### ISSUE THREAD

**Issue by alidcastano** [adonisjs/adonis-auth#68]
Is there a reason the generated token type is lowercase? I'm trying to set the header as `jwt.type + jwt.token` (`jwt` representing the generated token from `auth.generate`), but the approach doesn't work since `jwt.type` is `bearer` rather than `Bearer`.

**Comment by thetutlage** [comment]
The `bearer` is returned just for the programmatic use in the same code flow. I believe from client, you can feel free to `capitalize` it.

I just want to keep all identifiers lowercase and the intent of `type` was never to match what is accepted inside the header.

**Comment by alidcastano** [comment]
Ok no problem, I'll go ahead and close this then, thanks
