### ISSUE TITLE
Context.onReady is not a function

### ISSUE THREAD

**Issue by TeachMeAnything** [adonisjs/adonis-auth#69]
With the newest release, there seems to be a problem on startup. When I try to run the server it throws me the following error `TypeError: Context.onReady is not a function`. This even occurs when I don't define a Middleware on any routes.
   at AuthProvider.boot (M:\Dev\Server\node_modules\@adonisjs\auth\providers\AuthProvider.js:140:13)

**Comment by thetutlage** [comment]
Make sure you are on latest version of `@adonisjs/framework`
