### ISSUE TITLE
How send error message then auth failed in middleware auth? 

### ISSUE THREAD

**Issue by belozyorcev** [adonisjs/adonis-auth#7]
Hello. How create custom error message for auth-middleware? 
When false login - sended full error page, but me needing ```response.json({auth: 'error'})```.

Or needing write custom middleware?

**Comment by thetutlage** [comment]
@belozyorcev You need to catch errors inside `handleError` method. Also check http://adonisjs.com/docs/3.0/error-handling

**Comment by thetutlage** [comment]
Closing. Feel free to open issues for any bugs or problems you encounter.
