### ISSUE TITLE
Need possibility to switch hash algorithm in authorization

### ISSUE THREAD

**Issue by yariksav** [adonisjs/adonis-auth#70]
I connect authorization to my existing database with different hash logic of bcrypt (for example sha256 or md5... etc), but in adonis-auth use only Hash object with bcrypt algorithm. Can you make possibility to switch Hashes in authorization (Or some config in Hash object...)

https://github.com/adonisjs/adonis-auth/blob/8aa688685b7a3de35994a1c54b89fbb964cb3a72/src/Serializers/Lucid.js#L38-L40

https://github.com/adonisjs/adonis-auth/blob/8aa688685b7a3de35994a1c54b89fbb964cb3a72/src/Serializers/Lucid.js#L141-L146

**Comment by RomainLanz** [comment]
Hey @yariksav! 👋 

Using other algorithm than bcrypt to store password aren't secured.
I don't we will add a possiblity into the core to let you change it.

You can still fork this repository or create your own authentication inside your application.

**Comment by thetutlage** [comment]
I believe you can rollup your own serializer by extending the existing lucid serializer and simply override the `validatePassword` method 

I’ll share an example in a while ( not in front of computer)

**Comment by yariksav** [comment]
Hello, @RomainLanz, I understand that other algorithm is less-secure, but what what if I have old project with old database and other applications already work with this logic. 
Adm many-many of existing projects have old password security...
Also I can't recrypt passwords, because I don't have pure raw passwords

It will be fine to have some switcher. For example..
  session: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'session',
    uid: 'username',
    password: 'password,
    algorytm: 'bcrypt (default), sha256, md5'
  },

**Comment by hoangmy92** [comment]
Since your issue is related to hash, I think it has a several ways to solve:
- Retrieve the user and implement your way to validate the password on the controller/repository
- Write your own Hash Provider -> https://github.com/adonisjs/adonis-rally/blob/develop/bootstrap/app.js#L18
- Or do thetutlage's way

This is the guide to make new service provider http://adonisjs.com/docs/3.2/ioc-container#_service_providers

Enjoy!

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by mcordoba** [comment]
In this cases where you need to add compability with old password and you can decrypt them and encrypt with the new algorithm, you can use the login to do the magic.

So, when an old user log into the system, you have the plain password and you only have to encrypt it with the new algorithm and save it to database. You will end up with almost all your user migrated to a more secure password.
