### ISSUE TITLE
authentication issue with mongo db 

### ISSUE THREAD

**Issue by amrokhudair** [adonisjs/adonis-auth#71]
Hi
I use mongodb with adonis.
I used this package (https://www.npmjs.com/package/lucid-mongo) to integrate with mongodb.
When I login , the id of the user does not saved in the session
The error return:
Cannot store ObjectID data type to session store

**Comment by duyluonglc** [comment]
Hi @amrokhudair 
I'm owner of `lucid-mongo`
See this https://github.com/duyluonglc/lucid-mongo/issues/36

**Comment by amrokhudair** [comment]
Thank you for your replying.
it works
I have another question I don't no if it is related to first question.
When I use middleware like (auth) fir example ,and group some routes:
```
Route.group(() => {
    Route.get('/', 'DashboardController.index');
    Route.on('/newnotification').render('newnotification');
    Route.get('logout', 'SessionController.delete')
    Route.get('subscribers', 'SubscriberController.index');
    Route.post('send', 'NotificationController.send');
    Route.get('notifications', 'NotificationController.index');
}).middleware(['auth'])
```
When the user is logged in ,every thing works perfect.
put when user logged out, and it he want to access the same routes ,it return 
E_INVALID_SESSION: Invalid session
I want this page to return to login page when the session is invalid

**Comment by RomainLanz** [comment]
To do that you need to handle the exception and redirect from there.

http://adonisjs.com/docs/4.0/exceptions
