### ISSUE TITLE
Multiple Auth for same Authentication Scheme

### ISSUE THREAD

**Issue by anantab** [adonisjs/adonis-auth#73]
Is it possible to use same authentication scheme like session and have separate auth with multiple tables, for example for admin section and customer section. Or could it be session for admin and jwt for customer section?

**Comment by hoangmy92** [comment]
@anantab 
In the core of framework, they tried to find the suitable authentication provider (which was set on config/auth)
https://github.com/adonisjs/adonis-auth/blob/1.0.7/middleware/Auth.js#L29

So you just need to change the authenticator and it should work
http://www.adonisjs.com/docs/3.2/authentication#_switching_between_authenticators

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by mdjamilaj** [comment]
how to add multiple authenticator

**Comment by mcordoba** [comment]
Im doing something like this:

```
  jwt_customer: {
    serializer: 'lucid',
    model: 'App/Models/Customer',
    scheme: 'jwt',
    uid: 'email',
    password: 'password',
    options: {
      secret: Env.get('APP_KEY')
    }
  },

  jwt_user: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'jwt',
    uid: 'email',
    password: 'password',
    options: {
      secret: Env.get('APP_KEY')
    }
  },
````

Then, Im trying to switch between authenticators as specified here:
https://adonisjs.com/docs/4.1/authentication#_switching_authenticators

**Comment by gitsakil09** [comment]
How can I implement the multi model authentication in adonisJS v6? I would be grateful if you show me the way of achieving it.Thanks @thetutlage
