### ISSUE TITLE
plans to add CAS or LDAP auth? 

### ISSUE THREAD

**Issue by adampotocki** [adonisjs/adonis-auth#74]
I was wondering if you have plans to add CAS (2.0, 3.0 and SAML) and possibly LDAP auth to adonis-auth.

Awesome work on Adonis!
--

**Comment by thetutlage** [comment]
Sorry not now :)

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by Kledenai** [comment]
and now?

**Comment by himito** [comment]
and now ? xD
