### ISSUE TITLE
Example for creating auth in Adonis 4?

### ISSUE THREAD

**Issue by connor11528** [adonisjs/adonis-auth#76]
One of the reasons I was initially attracted to adonis was that generating authentication was as easy as one command. Now that seems to be broken! Is there an example of an Adonis 4 app with authentication?

**Comment by RomainLanz** [comment]
Hey @connor11528! 👋 

Why it seems broken?
Here's an example application with authentication https://github.com/adonisjs/adonis-blog-demo

**Comment by connor11528** [comment]
Okay I'll have to dig into this example. I cannot get login to work

Routes:

```
Route.get('login', 'UserController.loginPage')

Route.post('login', 'UserController.login')
Route.get('logout', 'UserController.logout')
```

Controller methods:

```
class UserController {
	async login ({ auth, request, response, session }) {
	    const { email, password } = request.all()

	    try {
	      console.log(email, password)
	      await auth.attempt(email, password)
	    } catch (e) {
	    	return response.redirect('login')
	    }

	    return view.render('tasks.index')
	}

```

Login form: 

```
<h1>Login form</h1>

<form method='post' action='/login'>

	{{ csrfField() }}
	<input type='text' placeholder='Username' name='username'>
	<input type='email' placeholder='Email' name='email'>
	<input type='password' placeholder='Password' name='password'>
	<button type='submit'>Login</button>
</form>
```

**Comment by thetutlage** [comment]
@connor11528 There are bunch of pieces of missing here.

1. Are you getting any exceptions?
2. How did u registered the user? A common problem people run into is, they hash the password twice, one time manually and 2nd time via hook

**Comment by connor11528** [comment]
@thetutlage I'm getting redirected to the login screen when trying to login. I registered a user using adonis repl like so:

```
await use('Database').table('users').insert({ email: 'connorleech@gmail.com', password: 'secret', username: 'connor11528' })
```

**Comment by thetutlage** [comment]
Yes it fails since password is not hashed, you need to use the hash provider to do it
