### ISSUE TITLE
Api Token Scheme

### ISSUE THREAD

**Issue by kevmt** [adonisjs/adonis-auth#77]
**Should be the Personal Api Token Scheme be referring to the one said on the API Docs:**

**_The personal API tokens become popular by Github (https://github.com/blog/1509-personal-api-tokens), to use a token for automated scripts, where it is not possible to manually type the email and password every time._**

**config/auth.js**
```
authenticator: 'api',
api: {
  serializer: 'lucid',
  scheme: 'api',
  model: 'App/Models/User'
},
```

Then I created the `api_token` for my test user which is in `tokens`
```
{ user_id: user.id, type: 'api_token', token: '123456', is_revoked: false }
```

But when I tried to access it using Postman;

```
GET /test HTTP/1.1
Host: 127.0.0.1:3333
Authorization: Bearer 123456
Cache-Control: no-cache
Postman-Token: c82707aa-6a50-1b50-44b5-2ff30059e8ed
```

It returns `401 Unauthorized`

```
E_INVALID_API_TOKEN: The api token is missing or invalid
```

I am not using JWT or such so, something wrong in the docs or I miss-understood it completely? or can someone tell me how to extend `@adonisjs/auth` so we can create something like a **Token** scheme? or a simple config like `encrypted: false` at `config/auth.js:api` just to have a flag disable the `Encryption.decrypt`

**Comment by thetutlage** [comment]
Why not `encrypt` the token before saving it

```js
Encryption.encrypt('123456')
```

**Comment by kevmt** [comment]
@thetutlage Hi, that would be because the size of the token column is too short? I'm trying not to modify the defaults. If there is a way to extend that would be great!

**Comment by thetutlage** [comment]
Maybe update the migration and if the default size is causing the issue, then I am happy accepting a PR for same :)
