### ISSUE TITLE
Refresh tokens issue in scheme jwt with custom foreign keys

### ISSUE THREAD

**Issue by vinicius-batista** [adonisjs/adonis-auth#82]
So, when I try to refresh an user token show a query exception:
`error: column tokens.userid does not exist` 
Method try to access userid (all in lowercase) in tokens table, but the correct is userId.
This error show only in generateForRefreshToken.

Code example bellow. 

  ```javascript
//Model definition
class User extends Model {
    static boot () {
      super.boot()
      this.addHook('beforeCreate', 'User.hashPassword')
   }
    tokens () {
      return this.hasMany('App/Models/Token', 'id', 'userId')
    }
  }

  //controller
  async refreshToken ({ request, auth }) {
      const refreshToken = request.header('x-refresh-token')
      return await auth.generateForRefreshToken(refreshToken) 
  }
```

**Comment by thetutlage** [comment]
Did u modified the default foreign key?

**Comment by vinicius-batista** [comment]
In token scheme? Yes. I use auth method for attempt with refresh token and work correctly.

This error was throw when executing this method on Lucid Serializer.
https://github.com/adonisjs/adonis-auth/blob/develop/src/Serializers/Lucid.js#L158

**Comment by thetutlage** [comment]
Can u share the database you are using?

**Comment by vinicius-batista** [comment]
I'm using PostgreSQL

**Comment by thetutlage** [comment]
Okay, so that seems to be the issue, PostgreSQL converts keys to lowercase when not in double quotes `"`.

Lemme see what best I can do in this case

**Comment by thetutlage** [comment]
@vinicius-batista Fixed in https://github.com/adonisjs/adonis-lucid/commit/c7df2007a9294b4279187d4de293f47de65b845f
