### ISSUE TITLE
Revoke JWT refresh_token

### ISSUE THREAD

**Issue by irakliOrbis** [adonisjs/adonis-auth#89]
Can't find any info in the documentation how to get user's refresh tokens.
I have route `/auth/logout` which should handle revoking `refresh_token`s. I will pass `refresh_token` to this route but have no idea how can I get that token from the database as it is decoded there.

<img width="842" alt="screen shot 2018-01-18 at 10 23 02 am" src="https://user-images.githubusercontent.com/32687522/35105452-b784890c-fc39-11e7-9562-05943e5bd5ea.png">

Also if I revoke `refresh_token` does it mean that every time user logs in and logs out I will store refresh tokens? I think this table will be too large after sometimes with unnecessary data. Can this tokens be stored in `Redis`? Can I set auth data driver to `Redis`?

**Comment by thetutlage** [comment]
You can decrypt the token using `Encryption` provider. Also feel free to delete the token instead of toggling the `is_revoked` flag.

Adonis gives both options, since some apps wants to store historical tokens. However you can simply delete them.

```js
const decrypted = Encryption.decrypt(token)

await Token.query().where('token', decrypted).delete()
```

I will add `revoke` methods to the auth object soon

**Comment by irakliOrbis** [comment]
@thetutlage Thank you! It works for me.

**Comment by thetutlage** [comment]
Added methods to revoke tokens within the auth class. Will be released soon.

**Comment by tapankumar** [comment]
@thetutlage : When will the new version will be released with this new revoke method?
