### ISSUE TITLE
request.auth.attempt() returning error too soon

### ISSUE THREAD

**Issue by andrewdelprete** [adonisjs/adonis-auth#9]
**In the Authentication docs there is an example something like this:**

```
    * login (request, response) {
        const email = request.input('email')
        const password = request.input('password')
        const login = yield request.auth.attempt(email, password)

        if (login) {
            response.route('profile')
            return
        }

        response.unauthorized('Invalid credentails')
    }
```

**If the `email` or `password` is invalid an error comes back something like this:**
PasswordMisMatchException: Password does not match

The `attempt()` method doesn't allow the rest of the code to continue once it fails / throws error. So response.unauthorized('Invalid credentails') never fires. Any ideas?

**Comment by thetutlage** [comment]
You need to wrap the `attempt` method instead a try/catch block.

```javascript
try {
  const login = yield request.auth.attempt(email, password)
  response.route('profile')
} catch (e) {
  response.unauthorized('Invalid credentails')
}
```

and of course, based on the exception type, you can return contextual errors like `Email is incorrect` or `Password does not match`.

Also I will update the docs

**Comment by andrewdelprete** [comment]
Thank you so much! Really excited about this framework. Keep it up!

**Comment by thetutlage** [comment]
@andrewdelprete Closing the issue, please feel free to create new issue if you face any problems
