### ISSUE TITLE
Symbols not supported in hash

### ISSUE THREAD

**Issue by dunkdunk** [adonisjs/adonis-auth#91]
I'm having an issue with using symbols in passwords. If I use the following password when I register a user, everything is fine when I try to log in.

`3FivP3B9NUeFBchgXHL`

However, if I register with a password containing symbols, I get an error.

`3FivP3B9NUeFBc+hgX*HL`

```
PasswordMisMatchException: E_PASSWORD_MISMATCH: Cannot verify user password
```

Does something need to be configured in order to allow symbols to work with the hashing algorithm?

**Comment by thetutlage** [comment]
Seems to be working fine here.

<img width="811" alt="screen shot 2018-01-25 at 11 52 33 am" src="https://user-images.githubusercontent.com/1706381/35373822-47eb38d8-01c6-11e8-9f77-3cc042a4c587.png">

You are sure you receive the right password and you are not double hashing the password before saving it?

**Comment by dunkdunk** [comment]
The issue is actually that the password I used with symbols, `3FivP3B9NUeFBc+hgX*HL`, is too long. The hash is working just fine. The issue I ran into is because of a character limit in my initial User migration.
