### ISSUE TITLE
Logout seems not working

### ISSUE THREAD

**Issue by thardraved** [adonisjs/adonis-auth#94]
So I have this simple auth controller:
```javascript
class AuthController {
  async login ({ request, response, auth, session }) {
    const userData = request.only(['username', 'password', 'rememberMe'])

    try {
      await auth
        .remember(typeof userData.rememberMe != 'undefined')
        .attempt(userData.username, userData.password)

      return response.redirect('/')
    } catch (err) {
      console.log(err)
      session.flashOnly(['username'])
      session.flash({ msg: 'User not found or password is incorrect.' })

      return response.redirect('back')
    }
  }

  async logout ({ response, auth }) {
    await auth.logout()

    return response.redirect('/')
  }
}
```
When logging in with remember token, everythin looking good, but when I try to log out – remember token stays in table and I can't log in again. (E_CANNOT_LOGIN: Cannot login multiple users at once...)
Even after logging in like that and then logging out, it's impossible to log in again
```javascript
async store ({ request, response, auth }) {
    const userData = request.only(['email', 'password', 'username'])
    const user = await User.create(userData)

    await auth
      .remember(true)
      .login(user)

    // TODO: set redirect to last visited url
    return response.redirect('/')
  }
```
Am I doing something wrong?

**Comment by RomainLanz** [comment]
Hey @thardraved! 👋 

You may want to revoke the token.
http://adonisjs.com/docs/4.0/authentication#_revoking_tokens

**Comment by thetutlage** [comment]
Adonis revokes the token on logout itself.

It seems to be working fine for me, here's the dummy app for same https://github.com/thetutlage/auth-issue-94

**Comment by thardraved** [comment]
Yeah, I've moved almost all code to clean install and all worked as expected. Maybe I've screwed up somewere though have no idea where. I hate this programming magic .__.

**Comment by fabianomg** [comment]
try {
      let logado = await auth.check()
      if (logado) {

        const user = await User.query()
          .where('username', auth.user.username)
          .first()

        if (user.level == 1) {

          return response.route('/admin')
        }
        if (user.level == 2) {

          return response.route('/')
        }
      }
    } catch (error) {
      return view.render('auth.login')
    }
