### ISSUE TITLE
forgot password?

### ISSUE THREAD

**Issue by stoplion** [adonisjs/adonis-auth#95]
Is reset password / reset token in Adonis?

**Comment by antwaanvh** [comment]
Not to my knowledge. I've implemented something similar to Laravel [here](https://github.com/antwaanvh/api-reset-password),  if you need it.

I plan on packaging it up.

**Comment by RomainLanz** [comment]
Hey @stoplion! 👋 

Could you elaborate?
You mean the `forget my password` functionality?

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.

**Comment by glenndevenish** [comment]
Hello, a `forgot my passord` feature with a way of resetting with a token would be great... Has this been implemented anywhere?

**Comment by RomainLanz** [comment]
Please, take a look at https://github.com/adonisjs/adonis-persona

**Comment by glenndevenish** [comment]
Brilliant, thanks @RomainLanz
