### ISSUE TITLE
Handle auth exceptions

### ISSUE THREAD

**Issue by hugomarisco** [adonisjs/adonis-auth#97]
I'm trying to handle the authentication exceptions on my wildcard exception handler but because the exceptions thrown by adonis-auth have themselves handlers I never get the chance to do it.

Is there a way to instruct the auth provider to let the exceptions go through? (I've looked for some sort of flag in the code but couldn't find anything).

Thank you

**Comment by RomainLanz** [comment]
Hey @hugomarisco! 👋 

Which version of `adonis-framework` are you using?
There's a change about how exceptions are handled with the latest version that may help you.

http://adonisjs.com/docs/4.1/upgrade-guide#_exception_handling

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.

**Comment by hugomarisco** [comment]
Hello @RomainLanz sorry for the late response, I didn't receive any notification.

I can confirm it's working after upgrading to the latest version of `adonis-framework`.

Thank you!
